package com.camplink.entity;

public enum NotificationType {
    ORDER_PLACED, ORDER_CONFIRMED, ORDER_DELIVERED,
    ORDER_CANCELLED, PAYMENT_CONFIRMED, MESSAGE,
    REQUEST_ACCEPTED, REQUEST_FULFILLED, OTHER
}
